# for CPE329 assignment 4
# compiler
CC = g++

# compiler flags
CFLAGS = 

# name of the output file
TEST1 = ecuTest

# name of file sources 
SRC1 = $(TEST1).cpp
#SRC2 = $(TARGET2).c 

# header file directories
#HEADERS = -I /home/alexpink/msp430/assignment5

all: $(TEST1) 

$(TEST1):
	$(CC) $(CFLAGS) -o $(TEST1).o $(SRC1) -lgtest 
$(TEST2):
	$(CC) $(CFLAGS) -o $(TEST2).o $(SRC2)
